# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  schedule:
    - cron: '00 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: node app.js
    env:
        NEST_EMAIL: ${{ secrets.NEST_EMAIL }}
        NEST_EMAIL_PASSWORD: ${{ secrets.NEST_EMAIL_PASSWORD }}
        COZE_API_KEY: ${{ secrets.COZE_API_KEY }}
        COZE_BOT_ID: ${{ secrets.COZE_BOT_ID }}
